using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using SilverAssertions;
using Xunit;
using static CodeBrix.PostgresClient.Tests.TestUtil;

namespace CodeBrix.PostgresClient.Tests; //was previously: Npgsql.Tests;

/// <summary>
/// This tests the .NET Framework DbDataReader schema/metadata API, which returns DataTable.
/// For the new CoreCLR API, see <see cref="ReaderNewSchemaTests"/>.
/// </summary>
public abstract class ReaderOldSchemaTests(SyncOrAsync syncOrAsync) : SyncOrAsyncTestBase(syncOrAsync)
{
    [Fact]
    public async Task primary_key_composite()
    {
        //Arrange
        using var conn = await OpenConnectionAsync();
        var table = await GetTempTableName(conn);

        await conn.ExecuteNonQueryAsync($@"
CREATE TABLE {table} (
    field_pk1 INT2 NOT NULL,
    field_pk2 INT2 NOT NULL,
    field_serial SERIAL,
    CONSTRAINT {table}_pk PRIMARY KEY (field_pk1, field_pk2)
)", cancellationToken: TestContext.Current.CancellationToken);

        using var command = new PgSqlCommand($"SELECT * FROM {table}", conn);
        using var dr = command.ExecuteReader(CommandBehavior.KeyInfo);
        dr.Read();
        var dataTable = await GetSchemaTable(dr);

        //Act
        var keyColumns = dataTable.Rows.Cast<DataRow>().Where(r => (bool)r["IsKey"]).ToArray();

        //Assert
        keyColumns.Should().HaveCount(2);
        keyColumns.Count(c => (string)c["ColumnName"] == "field_pk1").Should().Be(1);
        keyColumns.Count(c => (string)c["ColumnName"] == "field_pk2").Should().Be(1);
    }

    [Fact]
    public async Task primary_key()
    {
        //Arrange
        using var conn = await OpenConnectionAsync();
        var table = await CreateTempTable(conn, "id SERIAL PRIMARY KEY, serial SERIAL");

        using var command = new PgSqlCommand($"SELECT * FROM {table}", conn);
        using var dr = command.ExecuteReader(CommandBehavior.KeyInfo);
        dr.Read();
        var metadata = await GetSchemaTable(dr);

        //Act
        var key = metadata.Rows.Cast<DataRow>().Single(r => (bool)r["IsKey"]);

        //Assert
        key["ColumnName"].Should().Be("id");
    }

    [Fact]
    public async Task IsAutoIncrement()
    {
        //Arrange
        await using var conn = await OpenConnectionAsync();
        await IgnoreOnRedshift(conn, "Serial columns not supported on Redshift");

        var table = await CreateTempTable(conn, "serial SERIAL, int INT");

        var command = new PgSqlCommand($"SELECT serial, int, 8 FROM {table}", conn);
        await using var reader = command.ExecuteReader(CommandBehavior.KeyInfo);

        //Act
        var rows = (await GetSchemaTable(reader)).Rows;

        //Assert
        rows[0]["IsAutoIncrement"].Should().Be(true);
        rows[1]["IsAutoIncrement"].Should().Be(false);
        rows[2]["IsAutoIncrement"].Should().Be(false);
    }

    [Fact]
    public async Task IsAutoIncrement_identity()
    {
        //Arrange
        await using var conn = await OpenConnectionAsync();
        await IgnoreOnRedshift(conn, "Serial columns not supported on Redshift");
        MinimumPgVersion(conn, "10.0", "IDENTITY introduced in PostgreSQL 10");

        var table =
            await CreateTempTable(conn, "identity1 INT GENERATED BY DEFAULT AS IDENTITY, identity2 INT GENERATED ALWAYS AS IDENTITY");

        await using var command = new PgSqlCommand($"SELECT identity1, identity2 FROM {table}", conn);
        await using var reader = command.ExecuteReader(CommandBehavior.KeyInfo);

        //Act
        var rows = (await GetSchemaTable(reader)).Rows;

        //Assert
        rows[0]["IsAutoIncrement"].Should().Be(true);
        rows[1]["IsAutoIncrement"].Should().Be(true);
    }

    [Fact]
    public async Task IsIdentity()
    {
        //Arrange
        await using var conn = await OpenConnectionAsync();
        await IgnoreOnRedshift(conn, "Identity columns not support on Redshift");
        MinimumPgVersion(conn, "10.0", "IDENTITY introduced in PostgreSQL 10");
        var table = await CreateTempTable(
            conn,
            "identity1 INT GENERATED BY DEFAULT AS IDENTITY, identity2 INT GENERATED ALWAYS AS IDENTITY, serial SERIAL, int INT");

        await using var cmd = new PgSqlCommand($"SELECT identity1, identity2, serial, int, 8 FROM {table}", conn);
        await using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SchemaOnly | CommandBehavior.KeyInfo, cancellationToken: TestContext.Current.CancellationToken);

        //Act
        var rows = (await GetSchemaTable(reader)).Rows;

        //Assert
        rows[0]["IsIdentity"].Should().Be(true);
        rows[1]["IsIdentity"].Should().Be(true);
        rows[2]["IsIdentity"].Should().Be(false);
        rows[3]["IsIdentity"].Should().Be(false);
        rows[4]["IsIdentity"].Should().Be(false);
    }

    [Fact]
    public async Task IsReadOnly()
    {
        //Arrange
        using var conn = await OpenConnectionAsync();
        var table = await GetTempTableName(conn);
        var view = await GetTempViewName(conn);

        await conn.ExecuteNonQueryAsync($@"
CREATE TABLE {table} (id SERIAL PRIMARY KEY, int2 SMALLINT);
CREATE OR REPLACE VIEW {view} (id, int2) AS SELECT id, int2 + int2 AS int2 FROM {table}", cancellationToken: TestContext.Current.CancellationToken);

        var command = new PgSqlCommand($"SELECT id, int2 FROM {view}", conn);

        using var dr = command.ExecuteReader(CommandBehavior.SchemaOnly | CommandBehavior.KeyInfo);
        var metadata = await GetSchemaTable(dr);

        //Act
        var idRow = metadata.Rows.OfType<DataRow>().FirstOrDefault(x => (string)x["ColumnName"] == "id");

        //Assert
        idRow.Should().NotBeNull("Unable to find metadata for id column");
        var int2Row = metadata.Rows.OfType<DataRow>().FirstOrDefault(x => (string)x["ColumnName"] == "int2");
        int2Row.Should().NotBeNull("Unable to find metadata for int2 column");

        ((bool)idRow["IsReadonly"]).Should().BeFalse();
        ((bool)int2Row["IsReadonly"]).Should().BeTrue();
    }

    // ReSharper disable once InconsistentNaming
    [Fact]
    public async Task AllowDBNull()
    {
        //Arrange
        using var conn = await OpenConnectionAsync();
        var table = await CreateTempTable(conn, "nullable INTEGER, non_nullable INTEGER NOT NULL");

        using var cmd = new PgSqlCommand($"SELECT * FROM {table}", conn);
        using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SchemaOnly | CommandBehavior.KeyInfo, cancellationToken: TestContext.Current.CancellationToken);
        using var metadata = await GetSchemaTable(reader);

        //Act
        var nullableRow = metadata.Rows.OfType<DataRow>().FirstOrDefault(x => (string)x["ColumnName"] == "nullable");

        //Assert
        nullableRow.Should().NotBeNull("Unable to find metadata for nullable column");
        var nonNullableRow = metadata.Rows.OfType<DataRow>().FirstOrDefault(x => (string)x["ColumnName"] == "non_nullable");
        nonNullableRow.Should().NotBeNull("Unable to find metadata for non_nullable column");

        ((bool)nullableRow["AllowDBNull"]).Should().BeTrue();
        ((bool)nonNullableRow["AllowDBNull"]).Should().BeFalse();
    }

    [Fact, IssueLink("https://github.com/npgsql/npgsql/issues/1027")]
    public async Task without_result()
    {
        //Arrange
        using var conn = await OpenConnectionAsync();
        using var cmd = new PgSqlCommand("SELECT 1", conn);
        using var reader = await cmd.ExecuteReaderAsync(TestContext.Current.CancellationToken);
        reader.NextResult();

        //Act
        // We're no longer on a result
        var table = await GetSchemaTable(reader);

        //Assert
        table.Should().BeNull();
    }

    [Fact]
    public async Task precision_and_scale()
    {
        using var conn = await OpenConnectionAsync();
        using var cmd = new PgSqlCommand("SELECT 1::NUMERIC AS result", conn);
        using var reader = await cmd.ExecuteReaderAsync(TestContext.Current.CancellationToken);
        var schemaTable = await GetSchemaTable(reader);
        foreach (var myField in schemaTable.Rows.OfType<DataRow>())
        {
            myField["NumericScale"].Should().Be(0);
            myField["NumericPrecision"].Should().Be(0);
        }
    }

    [Theory]
    [InlineData(PrepareOrNot.NotPrepared)]
    [InlineData(PrepareOrNot.Prepared)]
    public async Task schema_only(PrepareOrNot prepare)
    {
        // if (prepare == PrepareOrNot.Prepared && IsMultiplexing)
        //     return;

        using var conn = await OpenConnectionAsync();
        var table = await CreateTempTable(conn, "name TEXT");

        var query = $@"
SELECT 1 AS some_column;
UPDATE {table} SET name='yo' WHERE 1=0;
SELECT 1 AS some_other_column, 2";

        using var cmd = new PgSqlCommand(query, conn);
        if (prepare == PrepareOrNot.Prepared)
            cmd.Prepare();
        using (var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SchemaOnly, cancellationToken: TestContext.Current.CancellationToken))
        {
            reader.Read().Should().BeFalse();
            var t = await GetSchemaTable(reader);
            t.Rows[0]["ColumnName"].Should().Be("some_column");
            reader.NextResult().Should().BeTrue();
            reader.Read().Should().BeFalse();
            t = await GetSchemaTable(reader);
            t.Rows[0]["ColumnName"].Should().Be("some_other_column");
            t.Rows[1]["ColumnName"].Should().Be("?column?");
            reader.NextResult().Should().BeFalse();
        }

        // Close reader in the middle
        using (var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SchemaOnly, cancellationToken: TestContext.Current.CancellationToken))
            reader.Read();
    }

    [Fact]
    public async Task BaseColumnName()
    {
        //Arrange
        using var conn = OpenConnection();

        conn.ExecuteNonQuery(@"
                CREATE TEMP TABLE data (
                    Cod varchar(5) NOT NULL,
                    Descr varchar(40),
                    Date date,
                    CONSTRAINT PK_test_Cod PRIMARY KEY (Cod)
                );
            ");

        var cmd = new PgSqlCommand("SELECT Cod as CodAlias, Descr as DescrAlias, Date FROM data", conn);

        using var dr = cmd.ExecuteReader(CommandBehavior.SchemaOnly | CommandBehavior.KeyInfo);

        //Act
        var dt = await GetSchemaTable(dr);

        //Assert
        dt.Rows[0]["BaseColumnName"].ToString().Should().Be("cod");
        dt.Rows[0]["ColumnName"].ToString().Should().Be("codalias");
        dt.Rows[1]["BaseColumnName"].ToString().Should().Be("descr");
        dt.Rows[1]["ColumnName"].ToString().Should().Be("descralias");
        dt.Rows[2]["BaseColumnName"].ToString().Should().Be("date");
        dt.Rows[2]["ColumnName"].ToString().Should().Be("date");
    }

    async Task<DataTable> GetSchemaTable(PgSqlDataReader dr) => IsAsync ? await dr.GetSchemaTableAsync() : dr.GetSchemaTable();
}

public sealed class ReaderOldSchemaTests_Sync() : ReaderOldSchemaTests(SyncOrAsync.Sync);
public sealed class ReaderOldSchemaTests_Async() : ReaderOldSchemaTests(SyncOrAsync.Async);
